baseURL: "http://ejemplo.com"
languageCode: es-es
title: Acme Corporation
theme: basico
author: 
  facebook: "https://facebook.com/example" 
  twitter: "https://twitter.com/example" 
  email: "contact@example.org" 
  name: "Acme Corporation" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 

menu:
  main: 
    - identifier: institutos
      name: institutos
      url: /centros/institutos
      pageRef: institutos
      weight: 600  
    - identifier: pelis
      name: Peliculas 
      url: /peliculas
      pageRef: pelis
      weight: 200
    - identifier: tv
      name: Canales 
      url: /television/canales
      pageRef: tv
      weight: 300
    - identifier: curriculum
      name: Curriculum 
      url: /curriculum
      weight: 220
    - identifier: viajes
      name: Viajes 
      url: /viajes
      weight: 250
    - identifier: Blog
      name: Blog 
      url: /Blog
      weight: 20
    - identifier: about 
      name: Acerca de 
      url: /about 
      weight: 100 
    - identifier: contact
      name: Contacto 
      url: /contacto 
      weight: 50  
params: 
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.      


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true